apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spark-application-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: argo-workflow-trigger
            image: argoproj/argoexec:v3.1.1
            command: ["sh", "-c"]
            args: ["argo submit --from workflow/spark-application --name spark-application-$(date +%Y%m%d%H%M%S)"]
          restartPolicy: OnFailure
