apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: HEAD
    chart: spark-operator
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: enableBatchScheduler
          value: "true"
  destination:
    namespace: spark-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
